apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
spec:
  values:
    tunnel:
      name: skolorna-api-tunnel
      ingress: |
        - hostname: api.skolorna.com
          httpHostHeader: api.skolorna.com
          service: http://kong-kong-proxy.kong:80
        # Return 404 if there are no matches
        - service: http_status:404
