apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/kong
  - ../base/cloudflared
  - ../base/metallb
  - ../base/notifications
  - ../base/prometheus
patchesStrategicMerge:
  - metallb.yaml
  - cloudflared.yaml
  - notifications.yaml
