kind: Service
apiVersion: v1
metadata:
  name: opnsense
spec:
  type: ExternalName
  externalName: opnsense.arn1.amcoff.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opnsense-proxy
  annotations:
    konghq.com/protocol: "https"
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /opnsense
        pathType: ImplementationSpecific
        backend:
          service:
            name: opnsense
            port:
              number: 443
