apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opengraph
  namespace: opengraph
spec:
  chart:
    spec:
      version: "<0.2.0"
  interval: 1m0s
  values:
    replicaCount: 2
