apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - podinfo.yaml
  - ingress-nginx.yaml
  - nfs-subdir-external-provisioner.yaml
  - runix.yaml
  - k8s-at-home.yaml