apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: menu-proxy
  namespace: menu-proxy
spec:
  releaseName: menu-proxy
  chart:
    spec:
      chart: menu-proxy
      sourceRef:
        kind: HelmRepository
        name: skolorna-kubernetes
        namespace: flux-system
  interval: 5m
  values:
    ingress:
      className: kong
      enabled: true
      annotations:
        konghq.com/strip-path: "true"
      hosts:
        - host: ""
          paths:
            - path: /v1/mp
              pathType: ImplementationSpecific
