apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "3.3.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    env:
      # -- Config dir
      DATA_FOLDER: "config"
      DATABASE_URL: "postgresql://vaultwarden:bcaTpfDK6r5xqe@postgresql13.postgresql13.svc.cluster.local/vaultwarden"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
#          kubernetes.io/tls-acme: "true"
        tls:
          - secretName: password-ericxliu-local-ca
            hosts:
              - password.ericxliu.local
        hosts:
          - host: password.ericxliu.local
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012

    persistence:
      config:
        enabled: true

