apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/opengraph
  - ../base/auth1
  - ../base/schedule
  - ../base/oden
  - ../base/skool
patchesStrategicMerge:
  - skool.yaml
  - oden.yaml
