apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
spec:
  type: discord
  channel: staging
  username: Flux
  secretRef:
    # kubectl -n flux-system create secret generic discord-url \
    # --from-literal=address=https://discordapp.com/api/webhooks/...
    name: discord-url
