apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/kong
  - ../base/cloudflared
  - ../base/metallb
  # - ../base/mayastor
  - ../base/notifications
  # - mayastor.yaml
  - ../base/prometheus
patchesStrategicMerge:
  - metallb.yaml
  - cloudflared.yaml
