apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 10.0.12.0/24
          avoid-buggy-ips: true # Mark .0 and .255 as unusable
