apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oden
  namespace: oden
spec:
  releaseName: oden
  chart:
    spec:
      chart: oden
      sourceRef:
        kind: HelmRepository
        name: skolorna-kubernetes
        namespace: flux-system
  interval: 5m
  values:
    oden-http:
      postgresSecretName: postgres

      ingress:
        className: kong
        enabled: true
        annotations:
          konghq.com/strip-path: "true"
        hosts:
          - host: ""
            paths:
              - path: /v0/oden
                pathType: ImplementationSpecific

    munin:
      postgresSecretName: postgres
      sentry:
        dsn: https://91125dfae60745f8ad9ced1fe94f0d8a@o1205646.ingest.sentry.io/6336084

    meilisearch:
      service:
        annotations:
          konghq.com/override: "meilisearch-health"

    #   ingress:
    #     className: kong
    #     enabled: true
    #     annotations:
    #       konghq.com/strip-path: "true"
    #     hosts:
    #       - host: ""
    #         paths:
    #           - path: /v0/search
    #             pathType: ImplementationSpecific
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: meilisearch-health
upstream:
  healthchecks:
    passive:
      healthy:
        successes: 3
      unhealthy:
        http_failures: 3
