apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opengraph
  namespace: opengraph
spec:
  releaseName: opengraph
  chart:
    spec:
      chart: opengraph
      sourceRef:
        kind: HelmRepository
        name: skolorna-kubernetes
        namespace: flux-system
  interval: 5m
  values:
    ingress:
      className: kong
      enabled: true
      annotations:
        konghq.com/strip-path: "true"
      hosts:
        - host: ""
          paths:
            - path: /v1/opengraph
              pathType: ImplementationSpecific
