name: e2e

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
        with:
          version: '0.31.1'
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.7.0
        with:
          cluster_name: flux
      - name: Install Flux 0.31.1 in Kubernetes Kind
        run: flux install --version=v0.31.1
      - name: Check flux resources
        run: |
          kubectl get all -n flux-system
          kubectl get deployments -n flux-system -o jsonpath="{range .items[*]}{.metadata.name}:{range .spec.template.spec.containers[*]}{.image}{'\n'}{end}{end}"
          kubectl get crds -A
      - name: Setup cluster reconciliation
        run: |
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=${GITHUB_REF#refs/heads/} \
          --username=${GITHUB_ACTOR} \
          --password=${{ secrets.GITHUB_TOKEN }} \
          --ignore-paths="clusters/**/flux-system/"
          flux create kustomization flux-system \
          --source=flux-system \
          --prune=true \
          --path=./clusters/staging
      - name: Display podinfo pods
        run: |
          kubectl get pods -n podinfo
          helm list --namespace podinfo
      - name: Install Flux latest in Kubernetes Kind
        run: flux install
      - name: Check flux resources
        run: |
          kubectl get all -n flux-system
          kubectl get deployments -n flux-system -o jsonpath="{range .items[*]}{.metadata.name}:{range .spec.template.spec.containers[*]}{.image}{'\n'}{end}{end}"
          kubectl get crds -A
      - name: Display podinfo pods after flux upgrade
        run: |
          kubectl get pods -n podinfo
          helm list --namespace podinfo  
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces
